const Tldr = require('../models/article').Tldr
const summary = require('node-tldr')
const Article = require('../models/article').Article

function createTldr (req, res) {
  const tldr = new Tldr(req.body)
  tldr.save((err, article) => {
    if (err) return res.status(401).json({error: '/tldr createTldr error 1'})
    res.status(200).json({message: 'tldr saved', tldr})
  })
}

function generateTldr (req, res) {
  const articleId = req.params.id
  const url = req.body.url
  Article.findById({_id: articleId}, function (err, article) {
    if (err) return res.status(401).json({error: '/tldr error cannot find article'})
    var currentArticle = article
    summary.summarize(url, function (result, failure) {
      if (failure) console.log('An error occured!')
      currentArticle.tldr = new Tldr({summary: result.summary})
      currentArticle.save((err, article) => {
        if (err) return res.status(401).json({error: '/tldr generateTldr error 1'})
        res.status(200).json({message: 'autogenerated tldr saved', article})
      })
    })
  })
}

function getAllTldr (req, res) {
  Tldr.find({}, function (err, TldrArray) {
    if (err) return res.status(401).json({error: '/getAllTldr error'})
    res.status(200).json(TldrArray)
  })
}

function getTldrById (req, res) {
  Tldr.findById({_id: req.params.tldr_id}, function (err, tldr) {
    if (err) return res.status(404).json({error: '/tldr getTldrById error 1'})
    res.status(200).json(tldr)
  })
}

function updateTldr (req, res) {
  Tldr.findById({_id: req.params.tldr_id}, function (err, tldr) {
    if (err) return res.status(401).json({error: '/tldr updateTldr error 1'})
    tldr.summary = req.body.summary
    tldr.save(function (err) {
      if (err) return res.status(401).json({error: '/tldr updateTldr error 2'})
      res.status(200).json({message: 'tldr updated! yay! ', tldr})
    })
  })
}

function removeTldr (req, res) {
  Tldr.findById({_id: req.params.tldr_id}, function (err, tldr) {
    if (err) return res.status(401).json({error: '/tldr cant find tldr to remove'})
    tldr.remove(function (err) {
      if (err) return res.status(401).json({error: '/tldr cant remove tldr'})
      res.status(200).json({message: 'tldr removed! Yay!'})
    })
  })
}

module.exports = {
  createTldr: createTldr,
  generateTldr: generateTldr,
  getAllTldr: getAllTldr,
  getTldrById: getTldrById,
  updateTldr: updateTldr,
  removeTldr: removeTldr
}
