const Tldr = require('../models/article').Tldr
const summary = require('node-tldr')
const Article = require('../models/article').Article

function createTldr (req, res) {
  const tldr = new Tldr(req.body)
  tldr.save((err, article) => {
    if (err) return res.status(401).json({error: '/tldr createTldr error 1'})
    res.status(200).json({message: 'tldr saved', tldr})
  })
}

function generateTldr (req, res) {
  const articleId = req.params.id
  const url = req.body.url
  Article.findById({_id: articleId}, function (err, article) {
    if (err) return res.status(401).json({error: '/tldr error cannot find article'})
    var currentArticle = article
    summary.summarize(url, function (result, failure) {
      if (failure) console.log('An error occured!')
      currentArticle.tldr = new Tldr({summary: result.summary})
      currentArticle.save((err, article) => {
        if (err) return res.status(401).json({error: '/tldr generateTldr error 1'})
        res.status(200).json({message: 'autogenerated tldr saved', article})
      })
    })
  })
}

module.exports = {
  createTldr: createTldr,
  generateTldr: generateTldr
}
